### ISSUE TITLE
error: [Transaction]: Error: No valid responses from any peers. Errors:

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/blockchain-hf-workspace#8]
```txt
...
2022-10-18T16:43:24.584769898Z Serving PUT /create-anchor :  2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkoZt2qMj5N9fHt54bu4Fctcibk5Pc8pCs6wwgAPEADgxKTc27gyQWYZ8sHbF3PVhKwLXyTX8YQwgW5kR8JiBVvb3AyZ26z3J8YQ6RF5iXcMnL9H8DfRCQZKyc1R9 4qnrBhooj78L2psbyjJ44LqFA4DA5wzCUMaNynEG1YoMUf32fKzu2GULw2VNUrARiBYcggMrLn2nUV953Zicx4AQ8jD1PkyCm4MjbHRUJvaGgHXJdXxJ3Nv6g14a2oj1VW43cZwxbYSkDvCwRwpxsopmYsBraZHX6iKxTCFGvCGFyigGisfdyFXpD1FU6e2TAoYFc2Jqxc1a7q9xWkFzMiUvGeSyLp74uaDUzu1tLP
2022-10-18T16:43:24.585489272Z Call CreateAnchor for : 2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkoZt2qMj5N9fHt54bu4Fctcibk5Pc8pCs6wwgAPEADgxKTc27gyQWYZ8sHbF3PVhKwLXyTX8YQwgW5kR8JiBVvb3AyZ26z3J8YQ6RF5iXcMnL9H8DfRCQZKyc1R9 and [object Object]
2022-10-18T16:43:34.549603007Z 2022-10-18T16:43:34.548Z - error: [Transaction]: Error: No valid responses from any peers. Errors:
2022-10-18T16:43:34.549627797Z     peer=peer0.org1.example.com:7051, status=500, message=error in simulation: failed to execute transaction b275261ffabc0d6a028a5d37ca1446bef74985514763ad7f1450ba580f65c32b: could not launch chaincode anchor_1.0:c3ac7c90059c1c1a20756d62f4b0b049dd352edc8bacade65b8535072be736b1: connection to anchor_1.0:c3ac7c90059c1c1a20756d62f4b0b049dd352edc8bacade65b8535072be736b1 failed: error cannot create connection for anchor_1.0:c3ac7c90059c1c1a20756d62f4b0b049dd352edc8bacade65b8535072be736b1: error creating grpc connection to peer0org1_anchor_ccaas:9999: failed to create new connection: context deadline exceeded
2022-10-18T16:43:34.549642427Z     peer=peer0.org2.example.com:9051, status=500, message=error in simulation: failed to execute transaction b275261ffabc0d6a028a5d37ca1446bef74985514763ad7f1450ba580f65c32b: could not launch chaincode anchor_1.0:c3ac7c90059c1c1a20756d62f4b0b049dd352edc8bacade65b8535072be736b1: connection to anchor_1.0:c3ac7c90059c1c1a20756d62f4b0b049dd352edc8bacade65b8535072be736b1 failed: error cannot create connection for anchor_1.0:c3ac7c90059c1c1a20756d62f4b0b049dd352edc8bacade65b8535072be736b1: error creating grpc connection to peer0org2_anchor_ccaas:9999: failed to create new connection: context deadline exceeded
2022-10-18T16:43:34.549647147Z     at newEndorsementError (/usr/src/app/node_modules/fabric-network/lib/transaction.js:74:12)
2022-10-18T16:43:34.549650417Z     at getResponsePayload (/usr/src/app/node_modules/fabric-network/lib/transaction.js:41:23)
2022-10-18T16:43:34.549653547Z     at Transaction.submit (/usr/src/app/node_modules/fabric-network/lib/transaction.js:255:28)
2022-10-18T16:43:34.549656876Z     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-10-18T16:43:34.549660176Z     at async Object.createAnchor (/usr/src/app/anchoring/createAnchor.js:5:20)
2022-10-18T16:43:34.553302279Z 2022-10-18T16:43:34.553Z - error: [Transaction]: Error: No valid responses from any peers. Errors:
2022-10-18T16:43:34.553309609Z     peer=peer0.org1.example.com:7051, status=500, message=error in simulation: failed to execute transaction ac4d8f45ecaa6bd6c55d44ed08a44b6ebd4a131887b03947430f5718fd3a92ca: could not launch chaincode anchor_1.0:c3ac7c90059c1c1a20756d62f4b0b049dd352edc8bacade65b8535072be736b1: chaincode registration failed: connection to anchor_1.0:c3ac7c90059c1c1a20756d62f4b0b049dd352edc8bacade65b8535072be736b1 failed: error cannot create connection for anchor_1.0:c3ac7c90059c1c1a20756d62f4b0b049dd352edc8bacade65b8535072be736b1: error creating grpc connection to peer0org1_anchor_ccaas:9999: failed to create new connection: context deadline exceeded
...
```

**Comment by joaoluis-pdm** [comment]
This seems to be dues to some containers ot being removed on stopDown.sh

```txt
pharmaledger@fgt-dev-pl:~$ docker ps -a
CONTAINER ID   IMAGE                       COMMAND                  CREATED       STATUS                       PORTS     NAMES
07557d85f427   anchor_ccaas_image:latest   "docker-entrypoint.s…"   3 weeks ago   Exited (137) 9 minutes ago             peer0org2_anchor_ccaas
6bbf3489bd61   anchor_ccaas_image:latest   "docker-entrypoint.s…"   3 weeks ago   Exited (137) 9 minutes ago             peer0org1_anchor_ccaas

pharmaledger@fgt-dev-pl:~$ docker rm 07557d85f427 6bbf3489bd61
07557d85f427
6bbf3489bd61

pharmaledger@fgt-dev-pl:~/blockchain-hf-workspace$ ./stopDown.sh 
```
